let flags = [
  [ "blue", "blue", "blue", "blue", "blue", "blue", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "white", "blue", "white", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "white", "blue", "white", "blue", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red"
  ],
  [
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
  ],
  [
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "yellow", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"
  ],
  [
    "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo",
    "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo",
    "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo",
    "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo",
    "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo", "indigo"
  ],
  [
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red"
  ],
  [
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow"
  ],
  [
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
  ],
  [
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "white", "white", "white", "white", "white", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
  ],
  [
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red"
  ], [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ], ["red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green"],[
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ], [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
  ],
  [
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
  ],
  [
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","yellow","green","green","green",
    "green","green","green","green","green","green","green","green","green","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green","green","green","green","yellow","yellow",
    "yellow","blue","blue","blue","yellow","yellow","yellow","green","green","green","green","green",
    "yellow","yellow","yellow","yellow","blue","white","blue","yellow","yellow","yellow","yellow","green",
    "green","green","green","green","yellow","yellow","yellow","blue","blue","blue","yellow","yellow",
    "yellow","green","green","green","green","green","green","green","green","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green","green","green","green","green","green",
    "green","green","yellow","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green"
  ],
  [
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red"
  ],
  [
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white",
    "yellow","white","white","white","white","white","white","white","white","white","white","white","white","yellow",
    "yellow","yellow","yellow","yellow","white","white","white","white","white","white","white","white","white","white",
    "white","yellow","white","yellow","white","white","white","white","white","white","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black"
  ],
  [
    "red","red","red","red","white","white","white","white","white","white","white","red","red","red","red",
    "red","red","red","red","white","white","white","red","white","white","white","red","red","red","red","red",
    "red","red","red","white","white","red","red","red","white","white","red","red","red","red","red","red",
    "red","red","white","white","red","red","red","white","white","red","red","red","red","red","red","red",
    "red","white","red","red","red","red","red","white","red","red","red","red","red","red","red","red","white",
    "white","red","red","red","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","red","white","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","red","white","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","white","white","white","white","red","red","red","red"
  ],
  [
    "red","red","white","red","white","red","red","blue","blue","blue","blue","blue","blue","blue","blue",
    "white","red","red","red","red","red","white","blue","blue","blue","blue","white","blue","blue","blue",
    "white","red","red","red","red","red","white","blue","blue","blue","blue","blue","blue","blue","blue",
    "red","red","white","red","white","red","red","blue","blue","white","blue","blue","blue","blue","blue","blue",
    "blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","white","blue","blue",
    "blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue",
    "blue","blue","white","white","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue",
    "blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","white","blue","blue","blue","blue",
    "blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue"
  ],
  [
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","blue","blue","blue",
    "blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue",
    "blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red"
  ],
  [
    "red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","green","green","green",
    "green","green","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","green",
    "green","green","green","green","red","red","red","red","red","yellow","yellow","yellow","yellow",
    "yellow","green","green","green","green","green","red","red","red","red","red","yellow","yellow",
    "yellow","yellow","yellow","green","green","green","green","green","red","red","red","red","red",
    "yellow","yellow","yellow","yellow","yellow","green","green","green","green","green","red","red",
    "red","red","red","yellow","yellow","yellow","yellow","yellow","green","green","green","green",
    "green","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","green","green",
    "green","green","green","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow",
    "green","green","green","green","green","red","red","red","red","red","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green"
  ],
  [
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","red","red","green","green","green","green",
    "green","green","green","green","green","green","green","green","red","red","red","red","green","green",
    "green","green","green","green","green","green","green","green","green","red","red","red","red","green",
    "green","green","green","green","green","green","green","green","green","green","green","red","red",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green"
  ],
  [
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "white", "green", "green", "white", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "white", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "white", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "white", "white", "green", "green", "white", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "white", "white", "white", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green"
  ],
  [
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white"
  ],
  ["red","red","white","blue","blue","blue","white","red","white","blue","blue","blue","white","red","red",
  "blue","white","red","red","white","blue","white","red","white","blue","white","red","red","white","blue",
  "blue","blue","blue","white","red","red","white","red","white","red","red","white","blue","blue","blue",
  "white","white","white","white","white","white","red","red","red","white","white","white","white","white","white",
  "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
  "white","white","white","white","white","white","red","red","red","white","white","white","white","white","white",
  "blue","blue","blue","white","red","red","white","red","white","red","red","white","blue","blue","blue",
  "blue","white","red","red","white","blue","white","red","white","blue","white","red","red","white","blue",
  "red","red","white","blue","blue","blue","white","red","white","blue","blue","blue","white","red","red"
  ]
];
let flagnames = ["USA", "Japan", "Argentina", "Latvia", "France", "Germany", "Denmark", "Sweden", "Norway", "Finland","Russia", "Italy", "Austria", "Hungary", "Belgium", "Armenia", "Mali", "Yemen", "Brazil", "Romania", "Egypt", "Canada", "Australia", "Columbia", "Guinea", "Bangladesh", "Pakistan", "England", "UK"];
