let flags = [
  [ "navy", "navy", "navy", "navy", "navy", "navy", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "navy", "white", "navy", "white", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "navy", "navy", "white", "navy", "white", "navy", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red"
  ],
  [
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
  ],
  [
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "yellow", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue"
  ],
  [
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white"
  ],
  [
    "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon",
    "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon",
    "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon",
    "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon",
    "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon", "maroon"
  ],
  [
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green",
    "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green",
    "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red"
  ],
  [
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red"
  ],
  [
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy"
  ],
  [
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "yellow", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
  ],
  [
    "red", "red", "red", "red", "white", "navy", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "navy", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "navy", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "white", "white", "white", "white", "white", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "white", "navy", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "navy", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "navy", "white", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "white", "white", "white", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "white", "white", "white", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "navy", "navy", "navy", "white", "white", "white", "white", "white", "white", "white", "white", "white",
  ],
  [
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red"
  ], [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ], 
  ["red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
  "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white",
  "white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white",
  "green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green",
  "green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green",
  "green","green","green","green","green"],
  [
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ], [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy", "navy",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
  ],
  [
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
  ],
  [
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
    "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue", "dodgerBlue",
  ],
  [
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","yellow","green","green","green",
    "green","green","green","green","green","green","green","green","green","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green","green","green","green","yellow","yellow",
    "yellow","navy","navy","navy","yellow","yellow","yellow","green","green","green","green","green",
    "yellow","yellow","yellow","yellow","navy","white","navy","yellow","yellow","yellow","yellow","green",
    "green","green","green","green","yellow","yellow","yellow","navy","navy","navy","yellow","yellow",
    "yellow","green","green","green","green","green","green","green","green","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green","green","green","green","green","green",
    "green","green","yellow","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green"
  ],
  [
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","dodgerBlue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red"
  ],
  [
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "navy","navy","navy","navy","navy","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red"
  ],
  ["red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"],
  [
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white",
    "yellow","white","white","white","white","white","white","white","white","white","white","white","white","yellow",
    "yellow","yellow","yellow","yellow","white","white","white","white","white","white","white","white","white","white",
    "white","yellow","white","yellow","white","white","white","white","white","white","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black"
  ],
  [
    "red","red","red","red","white","white","white","white","white","white","white","red","red","red","red",
    "red","red","red","red","white","white","white","red","white","white","white","red","red","red","red","red",
    "red","red","red","white","white","red","red","red","white","white","red","red","red","red","red","red",
    "red","red","white","white","red","red","red","white","white","red","red","red","red","red","red","red",
    "red","white","red","red","red","red","red","white","red","red","red","red","red","red","red","red","white",
    "white","red","red","red","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","red","white","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","red","white","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","white","white","white","white","red","red","red","red"
  ],
  [
    "red","red","white","red","white","red","red","navy","navy","navy","navy","navy","navy","navy","navy",
    "white","red","red","red","red","red","white","navy","navy","navy","navy","white","navy","navy","navy",
    "white","red","red","red","red","red","white","navy","navy","navy","navy","navy","navy","navy","navy",
    "red","red","white","red","white","red","red","navy","navy","white","navy","navy","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","white","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy",
    "navy","navy","white","white","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","white","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy"
  ],
  [
    "red","red","white","red","white","red","red","navy","navy","navy","navy","navy","navy","navy","navy",
    "white","red","red","red","red","red","white","navy","navy","navy","navy","red","navy","navy","navy",
    "white","red","red","red","red","red","white","navy","navy","navy","navy","navy","navy","navy","navy",
    "red","red","white","red","white","red","red","navy","navy","red","navy","navy","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","red","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","red","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy"
  ],
  [
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy",
    "navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","navy","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red"
  ],
  [
    "red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","green","green","green",
    "green","green","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","green",
    "green","green","green","green","red","red","red","red","red","yellow","yellow","yellow","yellow",
    "yellow","green","green","green","green","green","red","red","red","red","red","yellow","yellow",
    "yellow","yellow","yellow","green","green","green","green","green","red","red","red","red","red",
    "yellow","yellow","yellow","yellow","yellow","green","green","green","green","green","red","red",
    "red","red","red","yellow","yellow","yellow","yellow","yellow","green","green","green","green",
    "green","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","green","green",
    "green","green","green","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow",
    "green","green","green","green","green","red","red","red","red","red","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green"
  ],
  [
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","red","red","green","green","green","green",
    "green","green","green","green","green","green","green","green","red","red","red","red","green","green",
    "green","green","green","green","green","green","green","green","green","red","red","red","red","green",
    "green","green","green","green","green","green","green","green","green","green","green","red","red",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green"
  ],
  [
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "white", "green", "green", "white", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "white", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "white", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "white", "white", "green", "green", "white", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "white", "white", "white", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", 
    "white", "white", "white", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green"
  ],
  ["black","black","black","black","black","red","red","red","red","red","green","green","green","green","green","black","black","black","black","black","red","white","white","white","red","green","green","green","green","green","black","black","black","black","black","white","red","red","red","white","green","green","green","green","green","black","black","black","black","white","red","red","white","red","red","white","green","green","green","green","black","black","black","black","white","red","white","white","white","red","white","green","green","green","green","black","black","black","black","white","red","white","white","white","red","white","green","green","green","green","black","black","black","black","black","white","white","white","white","white","green","green","green","green","green","black","black","black","black","black","red","white","white","white","red","green","green","green","green","green","black","black","black","black","black","red","red","red","red","red","green","green","green","green","green"],
  [
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white",
  "white","white","white","white","white","white","white","red","white","white","white","white","white","white","white"
  ],
  ["red","red","white","navy","navy","navy","white","red","white","navy","navy","navy","white","red","red",
  "navy","white","red","red","white","navy","white","red","white","navy","white","red","red","white","navy",
  "navy","navy","navy","white","red","red","white","red","white","red","red","white","navy","navy","navy",
  "white","white","white","white","white","white","red","red","red","white","white","white","white","white","white",
  "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
  "white","white","white","white","white","white","red","red","red","white","white","white","white","white","white",
  "navy","navy","navy","white","red","red","white","red","white","red","red","white","navy","navy","navy",
  "navy","white","red","red","white","navy","white","red","white","navy","white","red","red","white","navy",
  "red","red","white","navy","navy","navy","white","red","white","navy","navy","navy","white","red","red"
  ],
  ["red","red","red","red","red","red","yellow","red","red","red","red","red","red","red","red","red","red","red","yellow","red","red","red","red","yellow","red","red","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red","red","red","red","red","red","red","yellow","yellow","yellow","red","red","red","red","red","red","red","red","red","red","red","yellow","red","red","red","yellow","red","red","yellow","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","yellow","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"],
  ["green","green","green","green","green","red","red","red","red","red","red","red","red","red","red","green","green","green","green","green","red","red","red","red","red","red","red","red","red","red","green","green","green","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red","red","red","green","green","green","yellow","red","red","red","yellow","red","red","red","red","red","red","red","green","green","green","yellow","red","navy","red","yellow","red","red","red","red","red","red","red","green","green","green","yellow","red","red","red","yellow","red","red","red","red","red","red","red","green","green","green","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red","red","red","green","green","green","green","green","red","red","red","red","red","red","red","red","red","red","green","green","green","green","green","red","red","red","red","red","red","red","red","red","red"],
  ["navy","navy","navy","white","navy","navy","navy","red","red","red","red","red","red","red","red","navy","white","white","white","white","white","navy","white","white","white","white","white","white","white","white","navy","navy","white","white","white","navy","navy","red","red","red","red","red","red","red","red","navy","white","navy","navy","navy","white","navy","white","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"],
  ["navy","navy","navy","white","navy","navy","navy","white","white","white","white","white","white","white","white","navy","white","white","white","white","white","navy","white","white","white","white","white","white","white","white","navy","navy","white","white","white","navy","navy","white","white","white","white","white","white","white","white","navy","white","navy","navy","navy","white","navy","white","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"],
  ["navy","navy","white","navy","navy","navy","red","red","red","red","red","red","red","red","red","navy","white","navy","navy","white","navy","red","red","red","red","red","red","red","red","red","navy","navy","navy","white","navy","navy","red","red","red","red","red","red","red","red","red","navy","navy","white","navy","navy","navy","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"],
  ["red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white"],
  ["maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white"],
  ["white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"],
  ["red","white","red","red","red","red","red","red","red","red","red","red","red","red","red","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","red","red","red","red","red","red","red","red","red","red","red","red","red","white","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","white","red","red","red","red","red","red","red","red","red","red","red","red","red","white","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","white","green","green","green","green","green","green","green","green","green","green","green","green","green","white","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","white","green","green","green","green","green","green","green","green","green","green","green","green","green"],
  ["white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","red","red","red","red","red","red","red","red","red","red","white","white","white","white","white","green","green","green","green","green","green","green","green","green","green","white","white","white","white","white","green","green","green","green","green","green","green","green","green","green","white","white","white","white","white","green","green","green","green","green","green","green","green","green","green","white","white","white","white","white","green","green","green","green","green","green","green","green","green","green"],
  ["green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green","green"],
  ["red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","yellow","yellow","yellow","red","yellow","red","red","yellow","yellow","yellow","red","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red","red","red","red","red","red","red","red","yellow","yellow","yellow","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red"]
];
let flagnames = ["USA", "Japan", "Argentina", "Estonia", "Latvia", "Lithuania", "France", "Germany", "Netherlands", "Denmark", "Sweden", "Norway", "Finland","Russia", "Italy", "Austria", "Hungary", "Belgium", "Armenia", "Mali", "Yemen", "Botswana", "Brazil", "Romania", "Chad", "Switzerland", "Egypt", "Canada", "Australia", "New Zealand", "Colombia", "Guinea", "Bangladesh", "Pakistan", "Afghanistan", "England", "UK", "China", "Portugal", "Liberia", "Chile", "Samoa", "Indonesia", "Monaco", "Poland", "Belarus", "Madagascar", "Saudi Arabia", "Roman Empire"];
