let flags = [
  [ "blue", "blue", "blue", "blue", "blue", "blue", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "white", "blue", "white", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "white", "blue", "white", "blue", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red"
  ],
  [
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "red", "red", "red", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
  ],
  [
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "yellow", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"
  ],
  [
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red"
  ],
  [
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow",
    "yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow","yellow"
  ],
  [
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "white", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "yellow", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
  ],
  [
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "white", "white", "white", "white", "white", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "white", "blue", "white", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "blue", "blue", "blue", "white", "white", "white", "white", "white", "white", "white", "white", "white",
  ],
  [
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "white", "white", "white", "white", "white", "red", "red", "red", "red", "red"
  ], [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ], [
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ], [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
  ],
  [
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
  ],
  [
    "green","green","green","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","yellow","green","green","green",
    "green","green","green","green","green","green","green","green","green","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green","green","green","green","yellow","yellow",
    "yellow","blue","blue","blue","yellow","yellow","yellow","green","green","green","green","green",
    "yellow","yellow","yellow","yellow","blue","white","blue","yellow","yellow","yellow","yellow","green",
    "green","green","green","green","yellow","yellow","yellow","blue","blue","blue","yellow","yellow",
    "yellow","green","green","green","green","green","green","green","green","yellow","yellow","yellow",
    "yellow","yellow","green","green","green","green","green","green","green","green","green","green",
    "green","green","yellow","green","green","green","green","green","green","green","green","green","green",
    "green","green","green","green","green","green","green","green","green","green","green","green"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
  ],
  [
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "black", "black", "black", "black", "black", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
    "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange", "orange",
  ],
  [
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red",
    "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "red", "red", "red", "red", "red"
  ],
  [
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
    "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black",
  ],
  [
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red",
    "blue","blue","blue","blue","blue","yellow","yellow","yellow","yellow","yellow","red","red","red","red","red"
  ],
  [
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red",
    "red","red","red","red","red","red","red","red","red","white","white","white","white","white","white","white",
    "yellow","white","white","white","white","white","white","white","white","white","white","white","white","yellow",
    "yellow","yellow","yellow","yellow","white","white","white","white","white","white","white","white","white","white",
    "white","yellow","white","yellow","white","white","white","white","white","white","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black","black",
    "black","black","black","black","black","black","black","black","black","black","black","black","black"
  ],
  [
    "red","red","red","red","white","white","white","white","white","white","white","red","red","red","red",
    "red","red","red","red","white","white","white","red","white","white","white","red","red","red","red","red",
    "red","red","red","white","white","red","red","red","white","white","red","red","red","red","red","red",
    "red","red","white","white","red","red","red","white","white","red","red","red","red","red","red","red",
    "red","white","red","red","red","red","red","white","red","red","red","red","red","red","red","red","white",
    "white","red","red","red","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","red","white","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","red","white","white","white","red","red","red","red","red","red","red","red","white","white",
    "white","white","white","white","white","red","red","red","red"
  ]
];
let flagnames = ["USA", "Japan", "Argentina", "France", "Germany", "Denmark", "Sweden", "Norway", "Finland","Russia", "Italy", "Brazil", "Austria", "Belgium", "Armenia", "Mali", "Yemen", "Romania", "", "", "", "", "", "Egypt", "Canada"];